### ISSUE TITLE
请问配置好了以后，为什么启动不了

### ISSUE THREAD

**Issue by aishuidedabai** [Clash-for-Apple/App#5]

**Comment by Arror** [comment]
1、编译的是iOS平台的？
2、是否成功安装到真机上？
3、如果2成功，是否添加了配置文件并且启用了VPN，如果是，请关闭VPN后，重新连接Xcode部署。
4、如果都不是，请提供具体的描述。

**Comment by aishuidedabai** [comment]
感谢你的回复：
1 ios平台。
2证书都配置好了。
3最后导入url，返回启动，第一次跳入设置安装，第二次点启动提示“正在断开链接”，且始终如此。

**Comment by Arror** [comment]
> 感谢你的回复：
> 1 ios平台，真机安装成功。
> 2证书都配置好了。
> 3最后导入url，返回启动，第一次跳入设置安装，第二次点启动提示“正在断开链接”，且始终如此。

1、部署的iOS版本是15+么？
2、可以在设置界面，日志等级设置为 信息，然后打开Mac的控制台App，过滤条件为PacketTunnel进程，看下日志有没有什么异常？

**Comment by aishuidedabai** [comment]
默认	15:15:02.455739+0800	nesessionmanager	Found 0 (0 active) registrations for com.Arror.Clash.PacketTunnel-iOS (com.apple.networkextension.packet-tunnel)

请问这个是证书配置错误吗

**Comment by Arror** [comment]
VPNManager.swift 第line 13 ~ 16，providerBundleIdentifier 要设置成你现在工程PacketTunnel-iOS的Identifier。

**Comment by Arror** [comment]
> iOS 15.4
> 
> 默认 15:15:02.455739+0800 nesessionmanager Found 0 (0 active) registrations for com.Arror.Clash.PacketTunnel-iOS (com.apple.networkextension.packet-tunnel)
> 
> 请问这个是证书配置错误吗

VPNManager.swift 第13 ~ 16行，providerBundleIdentifier要设置成你现在工程PacketTunnel-iOS的Identifier。
