### ISSUE TITLE
About Rule Code

### ISSUE THREAD

**Issue by aishuidedabai** [Clash-for-Apple/App#6]

**Comment by Arror** [comment]
修改配置文件rules部分不可以么？

**Comment by aishuidedabai** [comment]
你好，你说的应该是这里吧，这个配置文件应该是你自己定义的，我们不知道规则示例

        let config = """
        mixed-port: 8080
        mode: \(UserDefaults.shared.string(forKey: Clash.tunnelMode) ?? Clash.TunnelMode.rule.rawValue)
        log-level: \(UserDefaults.shared.string(forKey: Clash.logLevel) ?? Clash.LogLevel.silent.rawValue)
        """

**Comment by aishuidedabai** [comment]
您的实现过程都在ClashKit，非公开，代码只是写入配置，然后交给ClashKit，代码部分很简单，我本来想学习一下DNS代理部分，貌似ClashKit没有这个API

**Comment by Arror** [comment]
> 你好，你说的应该是这里吧，这个配置文件应该是你自己定义的，我们不知道规则示例
> 
> ```
>     let config = """
>     mixed-port: 8080
>     mode: \(UserDefaults.shared.string(forKey: Clash.tunnelMode) ?? Clash.TunnelMode.rule.rawValue)
>     log-level: \(UserDefaults.shared.string(forKey: Clash.logLevel) ?? Clash.LogLevel.silent.rawValue)
>     """
> ```

这里的配置是用来启动clash核心程序的，开启之后最终还是使用你下载或者导入的配置，只是会用上面的配置覆盖掉部分内容，比如prot、tunnel model以及log level。

**Comment by Arror** [comment]
> 您的实现过程都在ClashKit，非公开，代码只是写入配置，然后交给ClashKit，代码部分很简单，我本来想学习一下DNS代理部分，貌似ClashKit没有这个API

ClashKit是由clash-interface这个项目编译出来的xcframework后提供的Swift Package，也是公开的。地址：https://github.com/Clash-for-Apple/clash-interface。

你可以看到 func SetConfig(uuid string) error 这个接口，这里面我把DNS部分禁用了，你可以删除后，自行编译。

需要安装go、gomobile环境。

**Comment by Arror** [comment]
https://github.com/Clash-for-Apple/clash-interface/blob/f30a5dc25c24215ee7a3febbd18ecec9e55d7fb7/clash.go#L77

**Comment by aishuidedabai** [comment]
感谢你的耐心回答，你说的这个我在你的主页看到了

**Comment by aishuidedabai** [comment]
> > 你好，你说的应该是这里吧，这个配置文件应该是你自己定义的，我们不知道规则示例
> > ```
> >     let config = """
> >     mixed-port: 8080
> >     mode: \(UserDefaults.shared.string(forKey: Clash.tunnelMode) ?? Clash.TunnelMode.rule.rawValue)
> >     log-level: \(UserDefaults.shared.string(forKey: Clash.logLevel) ?? Clash.LogLevel.silent.rawValue)
> >     """
> > ```
> 
> 这里的配置是用来启动clash核心程序的，开启之后最终还是使用你下载或者导入的配置，只是会用上面的配置覆盖掉部分内容，比如port、tunnel model以及log level。

我没有看到你的覆盖操作，在PacketTunnel里也没看到clash加载了配置，难道他是通过uuid取的数据库里的配置文件？，这一切都是不可见的？

**Comment by Arror** [comment]
> > > 你好，你说的应该是这里吧，这个配置文件应该是你自己定义的，我们不知道规则示例
> > > ```
> > >     let config = """
> > >     mixed-port: 8080
> > >     mode: \(UserDefaults.shared.string(forKey: Clash.tunnelMode) ?? Clash.TunnelMode.rule.rawValue)
> > >     log-level: \(UserDefaults.shared.string(forKey: Clash.logLevel) ?? Clash.LogLevel.silent.rawValue)
> > >     """
> > > ```
> > 
> > 
> > 这里的配置是用来启动clash核心程序的，开启之后最终还是使用你下载或者导入的配置，只是会用上面的配置覆盖掉部分内容，比如port、tunnel model以及log level。
> 
> 我没有看到你的覆盖操作，在PacketTunnel里也没看到clash加载了配置，难道他是通过uuid取的数据库里的配置文件？，这一切都是不可见的？

App内下载或者导入配置文件的时候，会为每个配置文件建立一个以UUID为名称文件夹，用来存储配置文件以及下载的Proxy Provuder文件，ClashKit有一个接口ClashSetConfig，传入UUID，ClashKit会读取UUID命名的文件夹下的主配置文件，之后生成新的Config，覆盖部分内容，然后传给Clash核心
```swift
cfg, err := executor.ParseWithPath(path)
if err != nil {
	return err
}
constant.SetConfig(path)
CloseAllConnections()
cfg.General = basic.General
cfg.Profile.StoreSelected = false
```

**Comment by aishuidedabai** [comment]
感谢你的回复，那请问相同的uuid会进行覆盖吗

**Comment by Arror** [comment]
> 感谢你的回复，那请问相同的uuid会进行覆盖吗

会，不过UUID是由程序生成，应该不会重复吧。

**Comment by aishuidedabai** [comment]
您的代码我觉得，个人建议没必要弄个数据库来存储uuid和tagetURL，可以去掉它，只读取文件路径做删除修改。另外ClashPatchSelectGroup这个方法干嘛的，可以选择多个配置自动切换吗？好像不执行也可以正常运行

**Comment by Arror** [comment]
> 您的代码我觉得，个人建议没必要弄个数据库来存储uuid和tagetURL，可以去掉它，只读取文件路径做删除修改。另外ClashPatchSelectGroup这个方法干嘛的，可以选择多个配置自动切换吗？好像不执行也可以正常运行

使用数据库是为了未来设计存储一些额外信息，比如说，导入配置文件时，一并下载Proxy Provider、Rule Provider文件，这些文件的下载信息，更新信息等！而且CoreData也能更方便的驱动SwiftUI。

ClashPatchSelectGroup是针对每个策略组自主选择，如果不设置，clash默认第一个。

**Comment by aishuidedabai** [comment]
By The way 删除SwiftUI后，把版本调低到iOS11依然可以执行

**Comment by Arror** [comment]
> By The way 删除SwiftUI后，把版本调低到iOS11依然可以执行

嗯，是可以的，不过我想使用最新的SwiftUI来实现。
